<h1>New user</h1>
<hr>
<form action="/users" method="post">
    <div>   
        <label for="name">
            Nickname
            <input type="text" name="user[name]" value='<?= htmlspecialchars($data["name"]) ?>'>
        </label>
    </div>
    <?php if (!empty($errors["name"])) : ?>
        <div>
            <p><?=htmlspecialchars($errors["name"])?></p>
        </div>
    <?php endif; ?>
    <div>    
        <label for="name">
            Email
            <input type="text" name="user[email]" value='<?= htmlspecialchars($data["email"]) ?>'>
        </label>
    </div>
    <?php if (!empty($errors["email"])) : ?>
        <div>
            <p><?=htmlspecialchars($errors["email"])?></p>
        </div>
    <?php endif; ?>
    <input type="submit" value="Submit">
</form>

<p></p>

