<table>
      <thead>
          <tr>
              <th>id</th>
              <th>firstName</th>
              <th>lastName</th>
              <th>email</th>
          </tr>
      </thead>
      <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td>
                    <?= $user["id"] ?>
                </td>
                <td>
                    <?= $user["firstName"] ?>
                </td>
                <td>
                    <?= $user["lastName"] ?>
                </td>
                <td>
                    <?= $user["email"] ?>
                </td>
            </tr>
        <?php endforeach; ?>

      </tbody>
</table>