<?php if ($status === "404") : ?>
   <p> <?= "Page not found. Error 404."?> </p>
<?php else: ?>
   <table>
        <?php foreach ($user as $info) : ?>
            <?php foreach ($info as $key => $value) : ?>
                <tr>
                    <td>
                        <?= htmlspecialchars($key) ?> : <?= htmlspecialchars($value) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </table>
<?php endif; ?>



